version: '3.8'
services:
  backend:
    build: ./backend
    ports:
      - "127.0.0.1:5000:5000"
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app
  frontend:
    build: ./frontend
    ports:
      - "127.0.0.1:3000:3000"
    volumes:
      - ./frontend:/app
    depends_on:
      - backend
