name: medc-annotation-frontend
node: "18.20.4"  # 推荐的 LTS 版本，兼容 Vite 4 与 react-scripts 5
packageManager: npm
dependencies:
  axios: ^1.6.0
  react: ^18.0.0
  react-dom: ^18.0.0
  react-router-dom: ^6.30.1
  zustand: ^4.5.2
devDependencies:
  "@vitejs/plugin-react": ^4.7.0
  react-scripts: ^5.0.1
  vite: ^4.5.14
notes:
  - 生产构建使用 `vite build`，产物位于 `frontend/dist/`。
  - 生产环境建议使用 Nginx 或后端静态服务部署构建产物；临时预览可用 `npx serve -s dist`。
